name: hexcolorname
description: Flutter Package to convert color hex code to color name
version: 0.0.1
homepage: https://everycolorname.herokuapp.com/colorbyhex/FFFFFF

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
